name: Issue Template
description: Submit an issue
title: "ISSUE TITLE - CHANGE ME"
labels: ["task"]
assignees: "rockin-robinson"
body:
  - type: markdown
    attributes:
      value: |
        Please use the below form to submit an issue.
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: Describe the issue
      placeholder: Tell us what's up
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Low (1), Normal (2), or High (3) priority
      options:
        - 1 (Low)
        - 2 (Normal)
        - 3 (High)
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Due Date
      description: Please enter a due date for task completion in the form YYYY-MM-DD
      value: 2024-01-31
    validations:
      required: true
