name: totango

on:
  issues:
    types: [opened, closed, labeled]
  issue_comment:

jobs:
  get-task:
    # Prevent action from trying to parse issues that don't have the right label
    if: contains(github.event.issue.labels.*.name, 'task')
    runs-on: ubuntu-latest
    steps:
    - uses: jmassardo/issues-to-totango@fa4272b7d13c23f238f631f643d9446b1308e457
      with:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        ACTIVITY_TYPE: ${{ secrets.ACTIVITY_TYPE }}
        TOUCHPOINT_TAGS: ${{ secrets.TOUCHPOINT_TAGS }}
        TOUCHPOINT_TYPE: ${{ secrets.TOUCHPOINT_TYPE }}
